# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: math.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'math.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmath.proto\x12\x04math\"\x1f\n\rSquareRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0eSquareResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32y\n\x0bMathService\x12\x35\n\x06Square\x12\x13.math.SquareRequest\x1a\x14.math.SquareResponse\"\x00\x12\x33\n\x04\x43ube\x12\x13.math.SquareRequest\x1a\x14.math.SquareResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'math_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SQUAREREQUEST']._serialized_start=20
  _globals['_SQUAREREQUEST']._serialized_end=51
  _globals['_SQUARERESPONSE']._serialized_start=53
  _globals['_SQUARERESPONSE']._serialized_end=85
  _globals['_MATHSERVICE']._serialized_start=87
  _globals['_MATHSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
