# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import math_pb2 as math__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in math_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MathServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Square = channel.unary_unary(
                '/math.MathService/Square',
                request_serializer=math__pb2.SquareRequest.SerializeToString,
                response_deserializer=math__pb2.SquareResponse.FromString,
                _registered_method=True)
        self.Cube = channel.unary_unary(
                '/math.MathService/Cube',
                request_serializer=math__pb2.SquareRequest.SerializeToString,
                response_deserializer=math__pb2.SquareResponse.FromString,
                _registered_method=True)
        self.Sqrt = channel.unary_unary(
                '/math.MathService/Sqrt',
                request_serializer=math__pb2.SquareRequest.SerializeToString,
                response_deserializer=math__pb2.SquareResponse.FromString,
                _registered_method=True)


class MathServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Square(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cube(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sqrt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Square': grpc.unary_unary_rpc_method_handler(
                    servicer.Square,
                    request_deserializer=math__pb2.SquareRequest.FromString,
                    response_serializer=math__pb2.SquareResponse.SerializeToString,
            ),
            'Cube': grpc.unary_unary_rpc_method_handler(
                    servicer.Cube,
                    request_deserializer=math__pb2.SquareRequest.FromString,
                    response_serializer=math__pb2.SquareResponse.SerializeToString,
            ),
            'Sqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.Sqrt,
                    request_deserializer=math__pb2.SquareRequest.FromString,
                    response_serializer=math__pb2.SquareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'math.MathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('math.MathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MathService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Square(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/math.MathService/Square',
            math__pb2.SquareRequest.SerializeToString,
            math__pb2.SquareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cube(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/math.MathService/Cube',
            math__pb2.SquareRequest.SerializeToString,
            math__pb2.SquareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/math.MathService/Sqrt',
            math__pb2.SquareRequest.SerializeToString,
            math__pb2.SquareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
